version: '3.8'

services:
  sensor-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always
    depends_on:
      - prometheus

networks:
  monitoring:
